### PR TITLE
Make rAudio less Raspberry centric

### PR DESCRIPTION
**Pull request by fillods**
Other platforms like BeagleBone have no command vcgencmd, and optional /boot/config.txt ..

### CODE REVIEW

**Comment by rern** [comment]
Hi,

Please tell me how to identify BeagleBone programatically.

**Comment by fillods** [comment]
Hi,

Here is how to identify a BeagleBone:
```
grep -q BeagleBone /proc/device-tree/model && echo "Hi BB!"
```

For the curious one:
```
$ cat /proc/device-tree/model
TI AM335x BeagleBone Black
```
This is inspired by this doc for identifying RPi SoC (hint ^^): https://github.com/raspberrypi/documentation/blob/master/hardware/raspberrypi/revision-codes/README.md

**Comment by rern** [comment]
And what's the output of `lscpu`?

**Comment by fillods** [comment]
```
$ LANG=en_GB lscpu 
Architecture:        armv7l
Byte Order:          Little Endian
CPU(s):              1
On-line CPU(s) list: 0
Thread(s) per core:  1
Core(s) per socket:  1
Socket(s):           1
Vendor ID:           ARM
Model:               2
Model name:          Cortex-A8
Stepping:            r3p2
CPU max MHz:         1000.0000
CPU min MHz:         300.0000
BogoMIPS:            995.32
Flags:               half thumb fastmult vfp edsp thumbee neon vfpv3 tls vfpd32

```

**Comment by rern** [comment]
The request has been integrated into 20210414 update.

**Comment by fillods** [comment]
Works great! Thanks !

**Pull request closed without merging**
